// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7D_ap0UZwEEQct-GVRAEUUeHv-rWEhKw',
    appId: '1:472074932811:web:aeb6dfef4b17afad7573ce',
    messagingSenderId: '472074932811',
    projectId: 'equipment-checking-system-app',
    authDomain: 'equipment-checking-system-app.firebaseapp.com',
    storageBucket: 'equipment-checking-system-app.firebasestorage.app',
    measurementId: 'G-NE4DMSLERN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqR4YCF6CsV7jAhzh6x0xVuWRRZHxG2c',
    appId: '1:472074932811:android:fab4657ffc0b72167573ce',
    messagingSenderId: '472074932811',
    projectId: 'equipment-checking-system-app',
    storageBucket: 'equipment-checking-system-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpThQMC32RexjrjAUFDGAk8luM6eVJnnM',
    appId: '1:472074932811:ios:bcc7cb66c661ee837573ce',
    messagingSenderId: '472074932811',
    projectId: 'equipment-checking-system-app',
    storageBucket: 'equipment-checking-system-app.firebasestorage.app',
    iosBundleId: 'com.example.equipmentcheckingsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpThQMC32RexjrjAUFDGAk8luM6eVJnnM',
    appId: '1:472074932811:ios:bcc7cb66c661ee837573ce',
    messagingSenderId: '472074932811',
    projectId: 'equipment-checking-system-app',
    storageBucket: 'equipment-checking-system-app.firebasestorage.app',
    iosBundleId: 'com.example.equipmentcheckingsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7D_ap0UZwEEQct-GVRAEUUeHv-rWEhKw',
    appId: '1:472074932811:web:65976d095a0657997573ce',
    messagingSenderId: '472074932811',
    projectId: 'equipment-checking-system-app',
    authDomain: 'equipment-checking-system-app.firebaseapp.com',
    storageBucket: 'equipment-checking-system-app.firebasestorage.app',
    measurementId: 'G-S8Q4RHC3FT',
  );
}
